apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w1p38z1q7-nodejs
  janus-idp.io/tekton: w1p38z1q7-nodejs
  backstage.io/kubernetes-id: w1p38z1q7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w1p38z1q7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
