apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: w1p38z1q7-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w1p38z1q7-nodejs 
  name: w1p38z1q7-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: w1p38z1q7-nodejs 
